services:
  sas_robot_driver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "
      cd /root/sas_robot_driver_devel/src/
      && ls .
      && colcon build
      && source install/setup.bash
      && ros2 run sas_robot_driver sas_robot_driver_interface_example.py"